use std::{fs::File, io::Write};

fn main() {
    let mut crc_table = [0u32; 256];
    for n in 0..256 {
        let mut c = n as u32;
        for _ in 0..8 {
            if (c & 1) != 0 {
                c = 0xedb88320 ^ (c >> 1);
            } else {
                c = c >> 1;
            }
        }
        crc_table[n] = c;
    }

    File::create("src/_crc_table.rs")
        .expect("Failed to create _crc_table.rs")
        .write_all(
            format!(
                "// This file is auto-generated by build.rs. DO NOT EDIT\n\npub const CRC_TABLE: [u32; 256] = {:?};\n",
                crc_table
            )
            .as_bytes(),
        )
        .expect("Failed to write to _crc_table.rs");
}
