[package]
name = "pngss"
version = "0.1.0"
edition = "2024"

# description = "A subset implementation of PNG Encoder and Decoder"
# readme = "README.md"
# documentation = "https://neri.github.io/pngss/pngss/"
# homepage = "https://github.com/neri/pngss"
# repository = "https://github.com/neri/pngss"
# license = "MIT"
# categories = ["no-std"]
# keywords = ["graphics", "image"]
# exclude = [
#     "/.github/",
#     ".gitignore",
#     "/temp/",
#     "/examples/",
# ]

[dependencies]
crc = { path = "lib/crc" }
compress.workspace = true

[workspace.dependencies]
# compress = { path = "../compress" }
compress = { git = "https://github.com/neri/compress.git", rev = "c08efe8b2caed4caa523900ca0ebe40369768315" }

# [profile.release]
# debug = true
# panic = "abort"

[workspace]
members = [
    "examples/bench",
    "examples/idatdump",
    "examples/viewer",
]
